name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15"
          otp-version: "26"
      - run: mix deps.get
      - run: mix escript.build
      - run: mix escript.install --force
      - run: mix test

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15"
          otp-version: "26"
      - run: mix deps.get
      - run: mix escript.build
      - uses: softprops/action-gh-release@v2
        with:
          files: xamal
